# backend:
#     resource: "@BackendBundle/Controller/"
#     type:     annotation
#     prefix:   /

frontend:
    resource: "@FrontendBundle/Controller/"
    type:     annotation
    prefix:   /shop

app:
    resource: '@AppBundle/Controller/'
    type: annotation
